parameters: {}
environment: {}
packages:
  - name: tools
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: validate-links
        binary: false
        main: ""
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: fetch-rules
        binary: false
        main: ""
        runtime: nodejs:18
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
